# Generated by Django 5.1.15 on 2026-03-23 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(db_index=True, help_text="Identifiant unique de l'utilisateur (format: +225XXXXXXXXXX).", max_length=20, unique=True, verbose_name='numéro de téléphone')),
                ('role', models.CharField(choices=[('PRODUCTEUR', 'Producteur'), ('CLIENT', 'Client'), ('LIVREUR', 'Livreur')], default='CLIENT', max_length=15, verbose_name='rôle')),
                ('sub_role', models.CharField(blank=True, choices=[('PLANTEUR', 'Planteur'), ('PECHEUR', 'Pêcheur'), ('BERGER', 'Berger'), ('BOUCHER', 'Boucher'), ('ELEVEUR', 'Éleveur'), ('', 'Aucun')], default='', max_length=15, verbose_name='sous-rôle')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si le compte a été vérifié par SMS.', verbose_name='vérifié')),
                ('is_active_driver', models.BooleanField(default=False, help_text='Le livreur est-il actuellement disponible pour des courses ?', verbose_name='livreur actif')),
                ('has_refrigeration', models.BooleanField(default=False, help_text="Le livreur dispose-t-il d'un équipement de transport réfrigéré ?", verbose_name='équipement réfrigéré')),
                ('current_location_lat', models.FloatField(blank=True, null=True, verbose_name='latitude actuelle')),
                ('current_location_lng', models.FloatField(blank=True, null=True, verbose_name='longitude actuelle')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
