# Generated by Django 5.1.15 on 2026-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text="Jeton utilisé pour envoyer des notifications push vers l'appareil mobile.", max_length=255, null=True, verbose_name='Jeton Expo Push'),
        ),
    ]
