# Generated by Django 5.1.15 on 2026-03-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrant'), ('OUTBOUND', 'Sortant')], max_length=10, verbose_name='direction')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='numéro de téléphone')),
                ('raw_text', models.TextField(help_text='Contenu du SMS tel que reçu ou envoyé.', verbose_name='texte brut')),
                ('parsed_data', models.JSONField(blank=True, help_text='Résultat du parsing (produit, quantité, unité).', null=True, verbose_name='données extraites')),
                ('status', models.CharField(choices=[('RECEIVED', 'Reçu'), ('PARSED', 'Analysé'), ('PROCESSED', 'Traité'), ('ERROR', 'Erreur'), ('SENT', 'Envoyé')], default='RECEIVED', max_length=15, verbose_name='statut')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'journal SMS',
                'verbose_name_plural': 'journaux SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
