# Generated by Django 5.1.15 on 2026-03-23 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='quantité commandée')),
                ('unit_price', models.DecimalField(decimal_places=0, help_text='Prix national imposé au moment de la commande.', max_digits=10, verbose_name='prix unitaire (FCFA)')),
                ('total_product_amount', models.DecimalField(decimal_places=0, help_text='= quantité × prix unitaire.', max_digits=12, verbose_name='montant produits (FCFA)')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='frais de livraison (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=0, help_text='= montant produits + frais de livraison.', max_digits=12, verbose_name='montant total (FCFA)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Livreur assigné'), ('PICKED_UP', 'Récupérée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=15, verbose_name='statut')),
                ('delivery_address', models.TextField(help_text='Adresse textuelle de livraison.', verbose_name='adresse de livraison')),
                ('client_location_lat', models.FloatField(help_text='Latitude GPS du client.', verbose_name='latitude du client')),
                ('client_location_lng', models.FloatField(help_text='Longitude GPS du client.', verbose_name='longitude du client')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Non payé'), ('ESCROWED', 'En séquestre'), ('RELEASED', 'Libéré au producteur'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=15, verbose_name='statut de paiement')),
                ('transaction_id', models.CharField(blank=True, default='', help_text='Référence de paiement Wave / Orange Money / MTN MoMo.', max_length=100, verbose_name='ID transaction Mobile Money')),
                ('payment_provider', models.CharField(blank=True, default='', help_text='WAVE, ORANGE_MONEY, MTN_MOMO.', max_length=20, verbose_name='fournisseur de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('stock', models.ForeignKey(help_text='Stock du producteur à partir duquel la commande est passée.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
