# Generated by Django 5.1.15 on 2026-03-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ASSIGNED', 'Livreur assigné'), ('PICKED_UP', 'Récupérée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée'), ('DISPUTED', 'Litige en cours')], db_index=True, default='PENDING', max_length=15, verbose_name='statut'),
        ),
    ]
