# Generated by Django 5.1.15 on 2026-03-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assignée'), ('EN_ROUTE_PICKUP', 'En route vers le producteur'), ('PICKED_UP', 'Produit récupéré'), ('EN_ROUTE_DELIVERY', 'En route vers le client'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='ASSIGNED', max_length=20, verbose_name='statut')),
                ('delivery_fee', models.DecimalField(decimal_places=0, help_text='Part des frais de livraison revenant au livreur.', max_digits=10, verbose_name='frais de livraison (FCFA)')),
                ('otp_code', models.CharField(help_text='Code secret à 6 chiffres pour valider la fin de course.', max_length=6, verbose_name='code OTP')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='heure de ramassage')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='heure de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'LIVREUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
