# Generated by Django 5.1.15 on 2026-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_otp',
            field=models.CharField(default='000000', help_text='Code à donner au livreur par le CLIENT lors de la remise du colis.', max_length=6, verbose_name='code OTP Livraison'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_otp',
            field=models.CharField(default='000000', help_text='Code à donner au livreur par le PRODUCTEUR lors de la collecte.', max_length=6, verbose_name='code OTP Ramassage'),
            preserve_default=False,
        ),
    ]
