# Generated by Django 5.1.15 on 2026-03-23 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nom du produit')),
                ('category', models.CharField(choices=[('VIVRIER', 'Vivrier'), ('CARNE', 'Carné'), ('HALIEUTIQUE', 'Halieutique'), ('ELEVAGE', 'Élevage')], max_length=15, verbose_name='catégorie')),
                ('unit', models.CharField(choices=[('KG', 'Kilogramme'), ('TETE', 'Tête'), ('SAC', 'Sac'), ('CASIER', 'Casier'), ('TAS', 'Tas')], default='KG', max_length=10, verbose_name='unité de mesure')),
                ('national_price', models.DecimalField(decimal_places=0, help_text="Prix imposé par l'État / la plateforme en FCFA.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix national (FCFA)')),
                ('needs_refrigeration', models.BooleanField(default=False, help_text='Indique si le produit est périssable et nécessite un transport réfrigéré.', verbose_name='nécessite réfrigération')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, help_text='Produit disponible sur la plateforme.', verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité initiale')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité restante')),
                ('location_lat', models.FloatField(help_text='Latitude GPS du lieu de stockage.', verbose_name='latitude du stock')),
                ('location_lng', models.FloatField(help_text='Longitude GPS du lieu de stockage.', verbose_name='longitude du stock')),
                ('needs_refrigeration', models.BooleanField(default=False, help_text='Ce stock spécifique nécessite-t-il un transport réfrigéré ?', verbose_name='nécessite réfrigération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'PRODUCTEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL, verbose_name='producteur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('producer', 'product'), name='unique_producer_product_stock')],
            },
        ),
    ]
