# Generated by Django 5.1.15 on 2026-03-23 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dynamic_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remise dynamique (%)'),
        ),
    ]
