# Generated by Django 5.1.15 on 2026-03-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stock_dynamic_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogramme'), ('TETE', 'Tête'), ('SAC', 'Sac'), ('CASIER', 'Casier'), ('TAS', 'Tas')], default='KG', max_length=10, verbose_name='unité de mesure'),
        ),
    ]
