# Generated by Django 5.1.15 on 2026-03-26 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dynamic_discount',
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, help_text="Détails sur la qualité, la variété ou l'origine du produit.", verbose_name='description du stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Laissez vide pour utiliser le prix national. Ne peut pas dépasser le prix national.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix personnalisé (FCFA)'),
        ),
    ]
