# Generated by Django 5.1.15 on 2026-03-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_stock_dynamic_discount_stock_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo réelle du produit en stock.', null=True, upload_to='stocks/', verbose_name='photo du stock'),
        ),
    ]
