# Generated by Django 5.1.15 on 2026-03-27 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='grade',
            field=models.CharField(choices=[('A', 'Premium (Grade A)'), ('B', 'Standard (Grade B)'), ('C', 'Éco (Grade C)')], default='B', max_length=2, verbose_name='qualité / grade'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantité bloquée pour des commandes en cours de finalisation.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité réservée'),
        ),
        migrations.AddField(
            model_name='stock',
            name='variety',
            field=models.CharField(blank=True, help_text='Variété précise (ex: Banane Cavendish, Riz long grain).', max_length=100, verbose_name='variété'),
        ),
    ]
